name: Upgrade a q/stable cluster to q/candidate
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch: null

jobs:
  # a2b upgrade implies a/stable -> b/candidate release upgrade.
  q2q-upgrade-test:
    uses: ./.github/workflows/reusable-upgrade-test.yml
    with:
      job-name: Test quincy/stable to quincy/candidate upgrades
      release-channel: quincy/stable
      upgrade-mode: channel
      upgrade-channel: quincy/candidate
      verify-config: true
