name: Upgrade a q/stable cluster to r/candidate
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch: null

jobs:
  # a2b upgrade implies a/stable -> b/candidate release upgrade.
  q2r-upgrade-test:
    uses: ./.github/workflows/reusable-upgrade-test.yml
    with:
      job-name: Test quincy/stable to reef/candidate upgrades
      release-channel: quincy/stable
      upgrade-mode: channel
      upgrade-channel: reef/candidate
      verify-config: true
