name: Upgrade a r/stable cluster to squid/candidate
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch: null

jobs:
  r2s-upgrade-test:
    uses: ./.github/workflows/reusable-upgrade-test.yml
    with:
      job-name: Test reef/stable to squid/candidate upgrades
      release-channel: reef/stable
      upgrade-mode: channel
      upgrade-channel: squid/candidate
      verify-config: true
